import React, { useRef, useState } from "react";
import "./NightOwl.css";
import ReactPlayer from "react-player/youtube";
import images from "../../utils/images";
import {useNavigate} from "react-router-dom"

export default function NightOwl() {
  const listInnerRef = useRef();
  const [secondScreen, setSecondScreen] = useState(false);
  let navigate = useNavigate();

  function onScroll() {
    if (listInnerRef.current) {
      const { scrollTop } = listInnerRef.current;
      if (scrollTop > 200) setSecondScreen(true);
      if (scrollTop < 600) setSecondScreen(false);
    }
  }

  return (
    <div ref={listInnerRef} className="NightOwl-wrapper" onScroll={onScroll}>
      <div className="first-section-project">
        <div className="first-section-column">
          <div
            className="go-back"
            style={
              secondScreen
                ? { transform: "translateX(calc(90vw - 28%))" }
                : null
            }
            onClick={() => navigate("/")}
          >
            Go back home<img src={images.backArrow}></img>
          </div>
          <h1>Night Owl Showcase</h1>
          <ReactPlayer
            url="https://www.youtube.com/watch?v=sZWoFFf4kiU"
            controls={true}
            width={1280}
            height={720}
          />
        </div>
      </div>
      <div className="second-section-project">
        <h1>About</h1>
        <div>
          Due to the current casino space where you can't really see proof of
          true number randomness myself and some other blockchain, backend and
          frontend devs from all around the world are currently creating Night
          Owl, we aim to bring true privacy to casino gaming by connecting the
          Frontend with a Blockchain backend where all numbers generated by the
          blockchain can be seen by the user.
        </div>
        <div className="MyRole-container">
          <div className="MyRole-text-container">
            <h1>My Role</h1>
            <div style={{ fontSize: "0.8em" }}>
              Since every Frontend developer in the project is a Junior
              Developer someone had to take the leading role and act as Product
              Manager and that was me, my most relevant tasks are:
              <ul>
                <li>
                  Making sure the UI follows the stakeholders requests and keeps
                  a clean and attractive look
                </li>
                <li>
                  Taking care of most of the Git merges, conflics, pushes and
                  branches
                </li>
                <li>70%-75% of the code is done by myself.</li>
                <li>Maintaining the task board in Jira (Task manager)</li>
              </ul>
            </div>
          </div>
          <img id="MyRole-image" src={images.scrumBoard} />
        </div>
        <div className="MyRole-container">
          <div className="MyRole-text-container">
            <h1>Technologies</h1>
            <div className="ul-wrapper" style={{ fontSize: "0.8em" }}>
              <ul>
                <li>React</li>
                <li>JavaScript</li>
              </ul>
              <ul>
                <li>CSS/HTML</li>
                <li>Matomo</li>
              </ul>
            </div>
          </div>
          <img id="Technologies-image" src={images.webDesignIllustration} />
        </div>
        <h1>Relevant Links</h1>
        <div className="ul-wrapper">
          <ul>
            <li>
              <a href="https://github.com/nightowlcasino/NightOwl-Frontend/tree/Daniumy_latestUpdates">
                Github
              </a>
            </li>
            <li>
              <a href="https://twitter.com/NightOwlCasino">Twitter</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
}
